### PR TITLE
Update design note for flow testing

### PR DESCRIPTION
**Pull request by HiroyasuNishiyama**
This PR adds a more detailed suggestion to the flow testing design note on describing tests.

### CODE REVIEW

**Comment by knolleary** [comment]
@HiroyasuNishiyama thank you for these updates.

I think we need to be careful not to try and design the more complicated requirements before we get some of the basic framework in place.

We need to break the work down into iterations - what are the core set of features needed so we can release something to start getting feedback. We do not need to do everything in one go.

The proposal of having a special type of tab for creating test-only flows on is going to be quite complicated to achieve I think - and I would not say it is a must-have requirement for the first version.

You have identified lots of different event types - what is the absolute minimal set needed to run a basic test? Lets start with that and then iterate.


One of the big changes since the design was written is the plugin framework of Node-RED. We need to consider how the Test Framework can be provided as a plugin, rather than hard coded in the core and what that means for the design.

To do that, there will need to be a number of updates to the APIs provided by the runtime/editor for Plugins to use:

1. **Adding extra properties to nodes in the flow file**. 
   Plugins need a way to include extra properties on node objects. When the editor exports a node configuration, it needs to be told to include the test information.
2. **Adding custom panels to node edit dialogs**.
   In this case, the 'test' panel.
3. **Access to command-line args**
   If we want to support CLI mode of running tests, the plugin needs to be able to see the CLI args to know it is test mode at the start.

I'm sure there will be other things we identify as we go.

I am keen for us to iterate together on this work quite quickly. Given the work I have done with the Flow Debugger and Linter recently, I suggest the following next steps:

- I will create a repository for the Test Framework plugin and create the basic set of files for it. 
- **UI Work**
    1. Work on designing the test sidebar UI
    2. Create a proposal for how plugins can contribute edit panels
    3. Work on designing the node test panel
    4. Create a proposal for how plugins can register metadata for nodes
    5. Get the UI elements to store their data in the flow
- **Runtime Work**
    1. Design how the tests actually run...
    2. What other hooks/events/apis are needed to fully control the runtime properly

How does that sound? If you are happy with that approach, we can get this PR merged as-is and then iterate in the new repository itself.

I still have a fair amount of 2.0/Debugger work to complete at the moment, but I'll get the basic repository created and then we can use issues/discussions in that repo to carry on the conversation.

**Comment by knolleary** [comment]
I have created the basic plugin repository here: https://github.com/node-red/node-red-flow-tester

**Comment by HiroyasuNishiyama** [comment]
@knolleary Thank you for your comment on the design update.

> We need to break the work down into iterations - what are the core set of features needed so we can release something to start getting feedback. We do not need to do everything in one go.

I agree with your suggestion.  Let's start with the minimum functionality.

> You have identified lots of different event types - what is the absolute minimal set needed to run a basic test? Lets start with that and then iterate.

I think minimum set of events can be:
1. send
2. receive
for simple assertion type test cases.

We may need handling exception, timeout, etc. for complex cases.  But I think that we can implement them later.

> One of the big changes since the design was written is the plugin framework of Node-RED. We need to consider how the Test Framework can be provided as a plugin, rather than hard coded in the core and what that means for the design.

It's a good direction to implement testing feature with a plugin framework.

> I am keen for us to iterate together on this work quite quickly. Given the work I have done with the Flow Debugger and Linter recently, I suggest the following next steps:
> 
> * I will create a repository for the Test Framework plugin and create the basic set of files for it.
...
> How does that sound? If you are happy with that approach, we can get this PR merged as-is and then iterate in the new repository itself.

Your suggestion sounds very good approach.

> I still have a fair amount of 2.0/Debugger work to complete at the moment, but I'll get the basic repository created and then we can use issues/discussions in that repo to carry on the conversation.

Thank you for creating the repository.  First,  I will summarize a new design note for the minimum feature set in the repository.

**Comment by HiroyasuNishiyama** [comment]
@knolleary 
I have added a new simplified proposal of flow testing as an issue of `node-ref-flow-tester` issues.
I will appreciate it if you could look over it and let me know your thoughts. 
Also, please let me know if *issues* is not suitable place for discussion.

**Comment by knolleary** [comment]
Merging this design as the base-line for the ongoing work in https://github.com/node-red/node-red-flow-tester/

**Pull request merged**
