### PR TITLE
Add design note for lifecycle model of function node

### PR DESCRIPTION
**Pull request by HiroyasuNishiyama**
This PR adds design note for lifecycle model of enhanced function node.
This design note includes new lifecycle mode, using external NPM modules, and initialization/finalization support.

### CODE REVIEW

**Comment by knolleary** [comment]
As discussed at the F2F meeting, the plan is to first implement the "initialise" and "finalise" options and not do the "config" tab yet because that poses a lot of extra problems around dynamic handling of npm modules.

Having also looked at the code in the pull request (https://github.com/node-red/node-red/pull/2498) some addition design questions come to mind that need to be clearly documented. Given the discussion on this feature is now split between here and the implementation PR, I'm going to add some comments to both places. Some comments related to the conceptual design of the feature, and I'll those here. Some other comments relate to implementation details, which I'll add to the PR. If that split is not helpful, we can focus the conversation in one place or the other.


 What APIs are available to the init/final code?
   - can they access context?
   - can they call `node.send`? (In the current PR, the `node` object has not been made available)
   - can they return a Promise to allow for asynchronous work to be done before the node starts handling messages or the runtime stops.

What error handling is in place for the code?
 - if initialize throws an error (or if it can return a promise that rejects), does the node continue to process messages?

**Comment by HiroyasuNishiyama** [comment]
Thank you for your comments.

> * can they access context?

Contexts can be accessible. I think one of the roles of the initialization and exit codes is to initialize/cleanup contexts.

> * can they call `node.send`? (In the current PR, the `node` object has not been made available)

I think we should not allow calling `node.send`. because the receiving node may not be a ready.

> * can they return a Promise to allow for asynchronous work to be done before the node starts handling messages or the runtime stops.

The value returned by the initialization code will be ignored because there is no way to refer it in the function body.
However, it is possible to save promises in context and refer to it in the main body.


> What error handling is in place for the code?
> 
> * if initialize throws an error (or if it can return a promise that rejects), does the node continue to process messages?

Whether an error in the initialization code affects message processing is processing-dependent, so message processing is not stopped by an error in the initialization code.
Currently, if an error occurs, it will be logged as follows

```
2 Apr 13:12:21 - [error] [function:f369ddf5.eab71] ReferenceError: node is not defined
```

If error handling is required, the error information should be passed using context or other means.

**Comment by knolleary** [comment]
> The value returned by the initialization code will be ignored because there is no way to refer it in the function body.
>However, it is possible to save promises in context and refer to it in the main body.

I did not mean the function body should be able to access the returned promise of the initialise code.

I mean the Function node should wait to setup its on-message handler until the promise resolves. And if the promise rejects then it should not setup the on-message handler because the node is not able to handle messages.

> If error handling is required, the error information should be passed using context or other means.

I'm not sure what you mean. Yes it is possible for someone to write lots of error handling code and do lots of tricks with context to pass things around. I am more concerned about the cases where a user hasn't added proper error handling code - because lots of our users are not experienced JavaScript programmers who know how to do that. We need to make sure errors are clearly reported and the behaviour makes sense. This is why I think if the initialize code throws an uncaught exception the node should not be allowed to continue processing messages.

We need real examples of Function node code that demonstrate (and test) the different possible patterns here.

**Comment by HiroyasuNishiyama** [comment]
> I mean the Function node should wait to setup its on-message handler until the promise resolves. And if the promise rejects then it should not setup the on-message handler because the node is not able to handle messages.

I think your suggestion is appropriate.
After testing some code, I realized that we need support for two types of code: one that returns promise and one that uses callbacks.
Also, it would be nice to be able to handle multiple promises or callbacks.

- Example with Promise
```
function foo(ms, msg) {
    var p = new Promise((resolve, reject) => setTimeout(function() {
        console.log(msg);
        resolve();
    }, ms));
    return p;
}

var p0 = foo(3000, "ONE");
var p1 = foo(2000, "TWO");
return [p0, p1];
```

- Example with Callback
```
function foo(ms, msg) {
    var cb = asyncCallback();  // global function that creates callback
    setTimeout(function() {
        console.log(msg);
        cb(null, msg);
    }, ms);
}

foo(4000, "QUUX");
foo(2000, "QUUUX");
```

My concern is that the messages sent  before the initialization completes will be lost.
Should we queue these messages?

> I'm not sure what you mean. Yes it is possible for someone to write lots of error handling code and do lots of tricks with context to pass things around. I am more concerned about the cases where a user hasn't added proper error handling code - because lots of our users are not experienced JavaScript programmers who know how to do that. We need to make sure errors are clearly reported and the behaviour makes sense. This is why I think if the initialize code throws an uncaught exception the node should not be allowed to continue processing messages.

I understand your point.  Changed the "input" handler will not be registered when an error occurs in the initialization process.   Also, the error message has been changed to add the location information as follows.

```
[error] [function:10192335.51f6ed] SyntaxError: Unexpected token } (setup:line 5)
```

**Comment by knolleary** [comment]
We need to keep the API for the initialise function as clean and simple as possible, but also ensure it can be used properly.

I realise the init function should be defined as an `async function` - just as we do the body of the main function. That means users can use `await`- which can make for much cleaner code. 

I do not think it should be possible to return multiple promises. If a user needs to do that, they can either:
```
await p1;
await p2;
```
or
```
return Promise.all([p1,p2]);
```

I'm not sure about your callback suggestion. It doesn't feel a natural api to me. A more conventional api would have *one* `done` callback, but I don't know how to make that fit.

Can I propose we stick with Promises for now and we can get user feedback on if callbacks are needed - its easier to add then take away.

**Comment by HiroyasuNishiyama** [comment]
> Can I propose we stick with Promises for now and we can get user feedback on if callbacks are needed - its easier to add then take away.

It is no problem to limit initialization code to return single promise object.
Fixed document & current implementation according with this.
It also fixed following:
- messages received before completion of initialization are queued,
- value returned as a promise can be obtained by calling `getInitValue` function

**Comment by knolleary** [comment]
> value returned as a promise can be obtained by calling getInitValue function

I am not sure about this. It assumes the `init` function is expected to return a value - which it is not.

I think if the user needs the result of the promise they can store it themselves. If they are using async/await:

```
context.someValue = await myAsyncFunction();
```

or with a new Promise object:

```
return new Promise( (resolve, reject) => {
   // do some work
   // ...
   resolve("my value");
}).then(result => { context.someValue = result; });
```


---


I think you mentioned somewhere you implementation is queuing up calls to `node.send()`, but the design note doesn't describe the behaviour. Can you explain what you have implemented for this? How are the messages queued up and *when* do they get sent?

**Comment by HiroyasuNishiyama** [comment]
> I am not sure about this. It assumes the `init` function is expected to return a value - which it is not.

If no value is returned, `undefined` is used as in the normal JavaScript function.

> I think if the user needs the result of the promise they can store it themselves. If they are using async/await:

That's right.  However, as you commented at the beginning, using context seems not to be intuitive for non-experienced users.  Otherwise, the first idea to handle asynchronous processing using context can be used.

> I think you mentioned somewhere you implementation is queuing up calls to `node.send()`, but the design note doesn't describe the behavior. Can you explain what you have implemented for this? How are the messages queued up and _when_ do they get sent?

Added description on this behavior.
Messages received while async initialization is performed are kept by message handler of function node and processed in received order after the initialization completes.

**Comment by knolleary** [comment]
@HiroyasuNishiyama I see you have added a lot of content regarding installation of modules.

We had agreed the module stuff was not something we would look at for the initial version of this feature. The idea behind the design notes is not to have a PR that is doesn't get merged because new features are constantly being added.

Please can we try to get this design merged first? You can then add the module install ideas as a new PR that can be discussed separately.

As it stands, I cannot merge this PR with those extra changes in. I have very large concerns about the whole concept of allowing the Function node to install modules and any proposal is going to take a lot of work to figure out.

**Comment by HiroyasuNishiyama** [comment]
I agree with you. 
Reverted previous commit.
I will try to submit another PR after merge.

**Comment by knolleary** [comment]
Have been playing with the PR for this today.

There are some implementation specific comments I will add to that PR.

From a high level design, I don't think we should include `getInitValue` for this initial version. It gives the impression the user can only pass one value from the setup to the main function. But in reality they can pass whatever they want using `context`. I don't want to confuse matters by having two different ways of doing the same thing.

It does not stop us adding something like `getInitValue` in the future if we get feedback that something like that is needed.

**Comment by knolleary** [comment]
I have merged this design note because its implementation has been merged into `dev` for the 1.1.0 release.

We can now restart the conversation on npm module dependencies via a new PR that adds that content to the design.

Thanks! 🎉

**Comment by HiroyasuNishiyama** [comment]
Thank you for merging.
I have opened a new PR (https://github.com/node-red/designs/pull/31).
I would appreciate your comments on it.

**Pull request merged**
