### PR TITLE
add design note for pouchdb plugin

### PR DESCRIPTION
**Pull request by KazuhiroItoh**
I have created a design note for PouchDB Context Store Pulugin.
PouchDB is an abstraction layer and the database to be used is selected by the adapter.
PouchDB Context Store Pulugin applies a Node SQLite adapter and saves the data in SQLite.

### CODE REVIEW

**Review by dceejay — COMMENTED** [review]
Looks good. As PouchDB allows replication to other servers is it worth adding an example config to show that could be setup ? and indeed can the replication be targeted to only part of the database eg maybe only the global context part ? (and if not - then to explicitly mention that)

**Comment by KazuhiroItoh** [comment]
This design note considers using the SQLite plugin to save to a file with a specified path.
This is similar to a file plugin.
PouchDB can also use other DB plugins and replicate.
However, let them be considered in the future.

**Comment by dceejay** [comment]
Yes having that as a configurable option is good. SQLite is a good first choice for edge devices.
Ideally we should document/include an example configuration of how to set up the replication/backup to another server.

**Comment by KazuhiroItoh** [comment]
Updated the design notes for the PouchDB plugin.
Added information about replication to other databases.
I have also made it available for LevelDB and CouchDB, which PouchDB supports as standard.

I would appreciate it if you could also consider the repository to which the plugin will be merged.
I assume that "node-red-context-pouchdb" is used for now.

**Comment by knolleary** [comment]
Looks good - I'll create the repo as you suggest.

**Comment by knolleary** [comment]
https://github.com/node-red/node-red-context-couchdb

**Comment by knolleary** [comment]
urgh - got the name wrong. Let's try that agin.

**Comment by knolleary** [comment]
https://github.com/node-red/node-red-context-pouchdb

**Pull request merged**
