### PR TITLE
Migrate Flow Testing design note from wiki

### PR DESCRIPTION
**Pull request by HiroyasuNishiyama**
This PR migrate design note of *Flow Testing* from Wiki.

### CODE REVIEW

**Comment by YumaMatsuura** [comment]
@boneskull
We added another idea of flow testing - another_idea.md.
I appreciate it if you review these designs.

**Comment by knolleary** [comment]
Thank you for the alternative proposal. I think it solves a lot of the concerns
with the original idea and will be a good approach to take first. Can we update the PR
to make this the primary concept for the design, and the other idea as a possible future
piece? We can then get this merged and make some progress on it.


I think it would be helpful to have a summary of what type of testing this
feature will allow, before getting into the detail of *how* it is done.

Does the following sound like a good summary?

---

This feature allows a flow developer to create test cases for their flows that
can be run within the editor or by a CLI tool.


Within each node, the developer defines a series of test cases. The test case
can describe:
 - what message the node should send.
    - if this node is at the start of a flow, this message will be sent when the
      test case is run.
    - if this is a node in the middle of a flow, the message will be sent
      when the node receives an incoming message. This will by-pass the internal
      logic of the node. This allows the node to be stubbed out.
      It should also be possible to define a message to send when the test case
      is started - this will allow a test case to begin at any point in the flow

 - what message the node expects to receive.

 - some way of saying if an error is expected to be reported by the node
   for a given test case. 

---


I have some more specific comments on the proposal:

1. **Validating messages**.
   We need to provide some flexibility in how a developer describes the expected message. Some things should be stricter than others. For example, if the message contains a timestamp, that cannot be hardcoded. The proposal suggests using JSONata to evaluate to true/false. I think we need to see some example expressions that could be used for typical scenarios. That will help us to see if we need to provide a UI that can be used to provide more flexible rules for validating a message.

1. **Buttons on nodes**.
   From a UI design, I am not sure about this suggestion. I am
   concerned it will look quite messy with a lot of buttons overlapping the wiring.
   I suggest the Testing sidebar should be the priority and provide the main way
   for running tests. We can review whether buttons are needed later on.

2. **How to store the test configuration**.
   The default option is to include it in the main flow file. I wonder if it
   would be worth updating the Storage API to allow test configuration to be stored
   in a separate file - in the same way we do that with credentials.

**Comment by kazuhitoyokoi** [comment]
@knolleary I updated the design based on your comments. Could you check the updated design?

**Comment by binnes** [comment]
Some comments / feedback.

Test scenarios
I think the test framework in Node-RED needs to be able to perform both unit test (individual node) and integration test (flow as a whole).  With complex function nodes, sub flow nodes, or change nodes there can be complex functionality within a single node, that a test driven approach may expect to be tested in isolation.

It is not clear from the design document how comprehensive the testing can be with the proposed design and if a developer will have the flexibility needed.

**Unit tests**
Unit tests should work on a single node and msgs leading the node as part of the test will not be sent to connected nodes in the flow.
There should be the ability to add a number of tests, where each test provides an input and expected output pair (which should also be able to test for multiple output messages being created from a single input and also nodes that are able to send output out of different connectors can test correct messages are generated at appropriate output connector).  You should also be able to indicate if a given input should throw an exception rather than produce output.  These tests should be stand alone and specific to a node (not run as part of an integration test)

_Unit tests could also be very useful for node creators, as they allow a test suite to be included with the node source._

**Integration tests**
These tests test the flow as a whole.  There should be the option to add multiple integration test scenarios.

The integration test should be able to start the flow by generating output of a specific input node (e.g. http in node or mqtt node)

For each node there should be an option to provide :
- **check input** msg flowing into the node - typically assert tests, or test that node is executed/not executed/executed n times, etc...(call before a specific node is called)
- **stub node** (provide alternate functionality for a specific node - e.g. to prevent calling external services)
- **check output** typically assert test or verifying correct number of messages produced, etc.(called after a specific node completes)

The individual node configuration should be able to apply to all integrations tests (a common stub for all tests) or apply to an individual tests

As an example take an web endpoint handler, that will accept an http incoming request, if it contains valid data then write to a database and send the appropriate response back to the caller:
Test:
0. before tests run - stub nodes added to db out node and http out node, which do nothing to prevent external communication
1. Send a request with no data:
    - test will start with provided msg leaving http in node
    - check input msg on db node will ensure not attempt is made to write to db
    - check input msg on http out node will ensure correct response code is returned to caller
2. Send a request with invalid data:
    - test will start with provided msg leaving http in node
    - check input msg on db node will ensure not attempt is made to write to db
    - check input msg on http out node will ensure correct response code is returned to caller
3. Send request with valid data
    - test will start with provided msg leaving http in node
    - check input msg on db out node will validate the correct msg content
    - check input on http out node will ensure the correct response is sent to the caller

Comments on implementation
- I don't think the tests should be in the main flow file, as I think with testing disabled Node-RED should behave exactly as it does now.  a test_flow.json file should contain all the test config and code. When packaging an application for production use the tests should be able to be stripped out.
- The tests should not appear as part of the main flow, they should be created and configured off the main flow.  Possibly in a side panel, similar to how node properties are accessed
- Where possible Node-RED programming paradigm should be used to create tests rather than having to drop down to javascript, so to provide input I could drop an inject or change node into the config panel and configure it appropriately.  If I want to drop down to javascript then I would drag and drop a function node
- tests should be able to run as part of a DevOps toolchain, both unit and integration tests (headlerless run) in addition to being run manually within the Node-RED editor.  
- it may be appropriate to add some test specific nodes to the pallet, such as assert or msg received count to simplify test creation - not essential

**Comment by knolleary** [comment]
@binnes thanks for those comments.

@kazuhitoyokoi talking to Brian separately, I think we need to take a small step back from the Design to make sure we have properly identified the use cases for the test experience in Node-RED.

As Brian's feedback above describes, the topic of 'testing' covers a lot of areas and we need to make sure we have properly captured the requirements before we dive too deeply into implementation.

As it stands, the current design note does not give much detail on the use cases it will help address. I think the proposed features it describes are good and will be the right direction - but we miss the link back to use cases and requirements.

Brian has offered to help expand on the use cases and requirements here.

On that basis, I'm going to merge this PR into a testing branch. We can then continue to refine the design with further PRs.

**Pull request merged**
